### ISSUE TITLE
Warning: Unknown PAM module .The PowerBroker Identity Services PAM module cannot be configured for the pfexec service.

### ISSUE THREAD

**Issue by vpekelis28** [BeyondTrust/pbis-open#139]
joining domain works but idldap is not working after this error.

root@all-bmsdb-p01:/etc# domainjoin-cli join resldap.net vpekelis@idldap.net
Joining to AD Domain:   resldap.net
With Computer DNS Name: all-bmsdb-p01.resldap.net

vpekelis@IDLDAP.NET's password: 
Warning: System restart required
Your system has been configured to authenticate to Active Directory for the first time.  It is
recommended that you restart your system to ensure that all applications recognize the new settings.

Warning: Unknown PAM module
The PowerBroker Identity Services PAM module cannot be configured for the pfexec service. This
service uses the 'pam_tty_tickets.so.1' module, which is not in this program's list of known
modules. Please email PowerBroker Identity Services technical support and include a copy of
/etc/pam.conf or /etc/pam.d.

Warning: A resumable error occurred while processing a module
Even though the configuration of 'pam' was executed, the configuration did not fully complete.
Please contact PowerBroker Identity Services support.

SUCCESS
root@all-bmsdb-p01:/etc# modinfo pfexec
 Id Loadaddr   Size Info Rev Module Name
  0 10000000 970d96   -   0  unix ()
  1 1012c550 322a88   -   0  genunix ()
  2 103ed0f0     10   -   0  platmod ()
  3 10800000  19530   -   0  SPARC64-X ()
  5 1081a000   5140   1   1  specfs (filesystem for specfs)
  6 1081f0a0   3bc0   3   1  fifofs (filesystem for fifo)
  7 11bb8030  1abd0  50   1  dtrace (Dynamic Tracing)
  8 10822ba8   4698  16   1  devfs (devices filesystem)
  9 10826ff8  1d950   5   1  procfs (filesystem for proc)
 11 10843d00   3d78   1   1  TS (time sharing sched class)
 12 10847288    8e0   -   1  TS_DPTBL (Time sharing dispatch table)
 13 10847338  ebbc0   8   1  zfs (ZFS filesystem version 37)
 13 10847338  ebbc0 297   1  zfs (ZFS storage pool)
 14 109258a8   8630   -   1  swrand (Kernel Software-based Entropy P)
 15 10926cd0  2a210   -   1  kcf (Kernel Crypto Framework)
 16 1094f370   4070   -   1  sha1 (SHA1 Message-Digest Algorithm)
 16 1094f370   4070   -   1  sha1 (SHA1 Kernel SW Provider)
 17 109530e8   4060   -   1  idmap (ID Mapping kernel module)
 18 109570c0   4fc0 201   1  doorfs (doors)
 18 109570c0   4fc0 201   1  doorfs (32-bit door syscalls)
 19 1095bf38  1fd00 226   1  rpcmod (RPC syscall)
 19 1095bf38  1fd00 226   1  rpcmod (32-bit RPC syscall)
 19 1095bf38  1fd00   -   1  rpcmod (rpc interface str mod)
 20 10974c88   1df8   -   1  tlimod (KTLI misc module)
 21 10976a28   16e8   2   1  SDC (system duty cycle scheduling cl)
 22 10977e58   e8f8   -   1  sha2 (SHA2 Message-Digest Algorithm)
 22 10977e58   e8f8   -   1  sha2 (SHA2 Kernel SW Provider)
 23 10985f88   3538 201   1  rootnex (sun4 root nexus)
 24 109890f8    1c0 164   1  options (options driver)
 25 109891f8   10a8 205   1  sad (STREAMS Administrative Driver ')
 26 1098a068    a58 184   1  pseudo (nexus driver for 'pseudo' 1.31)
 27 1098a880    5e0   1   1  clone (Clone Pseudodriver 'clone')
 28 1098ac28  12aa8 211   1  scsi_vhci (SCSI VHCI Driver)
 29 1099d460  2a618   -   1  scsi (SCSI Bus Utility Routines)
 30 109c27d8    1e8 155   1  nulldriver (nulldriver 1.1)
 31 109c2880    cd8   -   1  scsi_vhci_f_asym_sun (f_asym_sun)
 32 109c3488   1d10   -   1  scsi_vhci_f_asym_lsi (f_asym_lsi)
 33 109c4ef8   1190   -   1  scsi_vhci_f_asym_emc (f_asym_emc)
 35 109c61f8    638   -   1  scsi_vhci_f_sym_hds (f_sym_hds)
 36 109c6760    5b0   -   1  scsi_vhci_f_sym (f_sym)
 37 109c6b78    b98   -   1  scsi_vhci_f_tpgs (f_tpgs)
 38 109c7650  2d168 212   1  sd (SCSI Disk Driver)
 39 109f1f18   72e0   -   1  cmlb (Common Labeling module)
 40 109f8978  22f18 144   1  mpt_sas (MPTSAS HBA Driver 00.00.00.30)
 41 10a1b518   4330 171   1  pcieb (PCIe bridge/switch driver)
 42 10a1f600  53a98   -   1  pcie (PCI Express Framework Module)
 43 10a720f0   2658   -   1  busra (Bus Resource Allocator (BUSRA))
 44 10a746e8   41d0   -   1  iovcfg (IOV Configuration Module)
 45 10a78430   7228 282   1  vnic (Virtual NIC)
 46 10a7f360   7d30  41   1  dld (Data-Link Driver)
 47 10a86a80   51a8   -   1  dls (Data-Link Services)
 48 10a8b8b0  38b20   -   1  mac (MAC Services)
 49 10ac3538  13bc0 189   1  px (Sun4v Host to PCIe nexus driver)
 50 10ad6968   be00   -   1  pcicfg (PCI and PCI Express Configurato)
 51 10ae22c8   3290   -   1  fcpci (FCode pci bus functions)
 52 10ae52d8   2668   -   1  fcodem (FCode framework 1.13)
 55 10af4580   d2e8   -   1  pxvec (Sun4v pxvec Interrupt Handler M)
 56 10b00dd8   2e20 309   1  emcpsf (PP SF 6.0.0.0.0)
 57 10b03a00  3a8d0 308   1  emcp (PP Driver 6.0.0.0.0)
 58 10b2de18  2cec8 242   1  ssd (SCSI SSA/FCAL Disk Driver)
 59 10b586e8  176c0  70   1  fcp (SunFC FCP v20160707-1.198)
 60 10b6f9a0 2c91e0   -   1  fctl (SunFC Transport v20160709-1.77)
 61 10b77c38   2810   -   1  emcpgpx (PP GPX Ext 6.0.0.0.0)
 62 10b7a2e0  36270   -   1  emcpmpx (PP MPX Ext 6.0.0.0.0)
 63 10bafe10   b098   -   1  emcpdm (PP DM Manager 6.0.0.0.0)
 64 10bbace8    200   -   1  emcpioc (PP PIOC 6.0.0.0.0)
 65 10bbae80   1568 281   1  vnex (sun4v virtual-devices nexus dri)
 66 10bbc178   2440  23   1  cnex (sun4v channel-devices nexus)
 67 10bbe310   f300   -   1  ldc (sun4v LDC module)
 68 12000000 1398c0 105   1  ip (IP STREAMS driver 1.47)
 68 12000000 1398c0   -   1  ip (IP STREAMS module 1.47)
 69 10bcd4b8   3ef0   -   1  md5 (MD5 Message-Digest Algorithm)
 69 10bcd4b8   3ef0   -   1  md5 (MD5 Kernel SW Provider)
 70 10bd10f8   35f0   -   1  hook (Hooks Interface v1.0)
 71 10bd4678   1990   -   1  neti (netinfo module)
 73 10bdb280   2b88   -   1  platsvc (sun4v Platform Services)
 74 10bddbe8 206e80   -   1  ds (Domain Services)
 75 10be4870   1770  47   1  drctl (DR Control pseudo driver)
 76 10be5d20  14b90   -   1  aes (AES Kernel SW Provider)
 77 121280a8  12a58   -   1  des (des encryption)
 77 121280a8  12a58   -   1  des (DES Kernel SW Provider)
 81 12181b20  14b88  17   1  dev (/dev filesystem)
 82 10ae7720   2ea0  18   1  ctfs (contract filesystem)
 83 10aea248   3368  15   1  mntfs (mount information file system)
 84 10aed500  166d8  11   1  tmpfs (filesystem for tmpfs)
 85 10bfdc50   1cd0  19   1  objfs (kernel object filesystem)
 86 12195f18   1090  20   1  sharefs (sharetab filesystem)
 87 12196ee0  1b5e8  74   1  fp (SunFC Port v20160709-1.114)
 99 122b31a8   1520   -   1  dada ( ATA Bus Utility Routines)
100 11bde6c8   6568 216   1  ses (SCSI Enclosure Services)
104 11800000  e1258 192   1  qlc (SunFC Qlogic FCA)
105 10af4468  42fb0   -   1  qlc_fw_2500 (SunFC Qlogic FCA-FW)
106 1238d458  2f5a8 114   1  iscsi (iSCSI Initiator v-1.66)
107 123bbdf0  2b0a8  24   1  sockfs (filesystem for sockfs)
108 123e4ef0   1558   -   1  ksocket (kernel socket module)
109 123e63f0   e110   -   1  idm (iSCSI Data Mover)
113 10bff538    970   -   1  fault_iso (sun4v Fault Isolation Services)
114 123f3c18   3200   -   1  dr_cpu (sun4v CPU DR)
115 123f6d30   1f68   -   1  dr_io (sun4v VIO DR)
116 123f8bf0   1a40   -   1  dr_mem (sun4v memory DR)
117 123fa500   1aa0   -   1  pm_rm (sun4v PM rsc mgr v1.1)
118 123fbeb8   1340   -   1  strplumb (STREAMS Plumbing Module)
119 109c5f88    4b0 106   1  ip6 (IP6 STREAMS driver)
120 123fcfd8    5b8 251   1  tcp (TCP STREAMS driver)
120 123fcfd8    5b8   -   1  tcp (TCP dummy STREAMS module)
120 123fcfd8    5b8   -   1  tcp (TCP socket module)
121 123fd280    4b8 252   1  tcp6 (TCP6 STREAMS driver)
122 123fd4d0    5b8 261   1  udp (UDP STREAMS driver)
122 123fd4d0    5b8   -   1  udp (UDP dummy STREAMS module)
122 123fd4d0    5b8   -   1  udp (UDP socket module)
123 123fd778    4b8 262   1  udp6 (UDP6 STREAMS driver)
124 123fd9c8    5b0  98   1  icmp (ICMP STREAMS driver)
124 123fd9c8    5b0   -   1  icmp (ICMP dummy STREAMS module)
124 123fd9c8    5b0   -   1  icmp (Rawip socket module)
125 123fdc68    4b0  99   1  icmp6 (ICMP6 STREAMS driver)
126 123fdeb0    508   6   1  arp (ARP STREAMS driver)
126 123fdeb0    508   -   1  arp (ARP STREAMS module)
127 118dace0   48b0   -   1  timod (transport interface str mod)
129 118dec08   4930   0   1  consconfig_dacf (Consconfig DACF)
130 118e2150   27e8  24   1  conskbd (conskbd multiplexer driver)
131 118e4570   44d0   -   1  kbtrans (kbtrans (key translation))
132 123fe118   18a8  25   1  consms (Mouse Driver for Sun 'consms' 5)
133 118e7530   4510 288   1  wc (Workstation multiplexer Driver )
134 118eaf70   9e18   -   1  tem (ANSI Terminal Emulator)
135 118efc60    b88 117   1  iwscn (Workstation Redirection driver)
136 118f0680  14330  56   1  ehci (USB EHCI Driver)
137 119047a0  3a180   -   1  usba (USBA: USB Architecture 2.0)
139 1194a938   f730 159   1  ohci (USB OpenHCI Driver)
140 11959ec0   1ef8 190   1  qcn (sun4v console driver)
142 11968018   a538   -   1  ibdm (InfiniBand Device Manager)
143 11972498  1edd0   -   1  ibtl (IB Transport Layer)
144 1198fef8  1b760   -   1  ibmf (IB Agent Interfaces 2.0)
151 11a28fd0   31f0 312   1  hcad (HCA Driver)
153 119cdac8   8800 103   1  iospc (IO Perf Counter Driver)
154 11a45dc0   ea10   -   1  pcbe.SPARC64-X (SPARC sun4v Performance Counter)
155 119d1440   29d0 124   1  kssl (Kernel SSL Interface)
159 1195bb28   aef0   1   1  elfexec (exec module for elf)
159 1195bb28   aef0   0   1  elfexec (32-bit exec module for elf)
165 123ff660    330  87   1  hubd (USB Hub Driver)
169 11967a10    408   -   1  zvmisc (kernel zone common driver code)
172 11ad6618   e890   -   1  ldterm (terminal line discipline)
173 11ae45f8   25c8   -   1  ttcompat (alt ioctl calls)
174 11ae6a20   1510 188   1  ptsl (tty pseudo driver slave 'ptsl')
175 11ae7ce0   1ea8 185   1  ptc (tty pseudo driver control 'ptc')
186 11b1d508   6c50 112   1  ipsecesp (IPsec ESP STREAMS driver)
186 11b1d508   6c50   -   1  ipsecesp (IPsec ESP STREAMS module)
187 11b23920  126f0 111   1  ipsecah (IPsec AH STREAMS driver)
187 11b23920  126f0   -   1  ipsecah (IPsec AH STREAMS module)
190 11b3df48   1d28 141   1  mm (memory driver)
191 11b3faf0   1628 249   1  sysmsg (System message redirection (fan)
192 11966ba0    930   0   1  cn (Console redirection driver)
193 11967d68    2b0  42   1  pipe (pipe(2) syscall)
193 11967d68    2b0  42   1  pipe (32-bit pipe(2) syscall)
194 11b40a10   1940   4   1  namefs (filesystem for namefs)
195 11b422a8   6880 182   1  portfs (event ports)
195 11b422a8   6880 182   1  portfs (32-bit event ports syscalls)
196 11967380    518   2   1  intpexec (exec mod for interp)
197 11b489f8   12d0 248   1  sysevent (sysevent driver)
198 11b49b58   2b88 197   1  rds (RDS STREAMS driver)
199 123ff850    980 131   1  log (streams log driver)
200 11b4be88   6d30 254   1  tl (TPI Local Transport (tl))
201 11b52590   4228 122   1  keysock (PF_KEY socket STREAMS driver)
201 11b52590   4228   -   1  keysock (PF_KEY socket STREAMS module)
202 11b561d8   5f50 234   1  spdsock (PF_POLICY socket STREAMS driver)
203 11b5bc20   2028  53   1  semsys (System V semaphore facility)
203 11b5bc20   2028  53   1  semsys (32-bit System V semaphore facil)
204 11b5db78   1720   -   1  ipc (common ipc code)
205 11b5f240   35b8  52   1  shmsys (System V shared memory)
205 11b5f240   35b8  52   1  shmsys (32-bit System V shared memory)
206 11b62708   7ea0   -   1  softmac (softmac module)
206 11b62708   7ea0 230   1  softmac (softmac driver)
208 11b81f10  29390   -   1  ibcm (IB Communication Manager)
209 11baad20    e60   -   1  cubic (cubic congestion control module)
210 119d6cd0    698   -   1  highspeed (highspeed congestion control mo)
211 11bab630    728   -   1  vegas (vegas congestion control module)
212 119d7050    520 204   1  rts (PF_ROUTE socket STREAMS driver)
212 119d7050    520   -   1  rts (PF_ROUTE socket module)
213 11a2bf90    ed8  12   1  fdfs (filesystem for fd)
214 11a2cd28   1368  30   1  cryptoadm (Cryptographic Administrative In)
215 11a2df48   3338   -   1  blowfish (Blowfish Kernel SW Provider)
216 11a31030   2f40   3   1  FX (Fixed priority sched class)
217 11967f70    2b8   -   1  FX_DPTBL (Fixed priority dispatch table)
218 11bd2830   7a18   -   1  camellia (Camellia Kernel SW Provider)
219 11a337b0    678 196   1  random (random number device)
220 11a33cc8    820  51   1  dump (crash dump driver)
221 11a343a0   1570 180   1  pool (pool driver)
222 11a357c0   2d98  13   1  bmc (BMC 1.13)
223 11bd9fb0   4940 278   1  vldc (sun4v Virtual LDC Driver)
224 11b358c0   6648  88   1  devinfo (DEVINFO Driver)
225 11be4b98   26b8 160   1  openeepr (OPENPROM/NVRAM Driver)
226 11be6cf8   10e8 125   1  kstat (kernel statistics driver)
227 11000000  410e8 119   1  ixgbe (Intel 10Gb Ethernet)
228 11be7c98   1860   -   1  mac_ether (Ethernet MAC plugin)
230 1103fb60  25b30 101   1  igb (Intel 1Gb Ethernet)
232 11bea560   8a70  68   1  fcoe (FCoE Transport v20140219-1.10)
233 11bf2d08   a6f0   5   1  aggr (Link Aggregation MAC)
234 11063f20   4538 279   1  vlds (Domain Services Driver)
237 11bfd418   1cd8  26   1  cpc (cpc sampling driver)
237 11bfd418   1cd8 179   1  cpc (cpc sampling system call)
237 11bfd418   1cd8 179   1  cpc (32-bit cpc sampling system call)
238 11bfd038    4e0  27   1  cpuid (cpuid driver)
239 110a77b8  111e8  28   1  crypto (Cryptographic Library Interface)
243 110815d8   15d8  48   1  ds_pri (Domain Services PRI Driver)
246 110a3020   4a48  64   1  fasttrap (Fasttrap Tracing)
250 110b97d0   1110  67   1  fcode (FCode driver)
262 7bc0d2c8    e00 139   1  mdesc (Machine Description Driver)
265 11be8698   1588 179   1  poll (/dev/poll driver)
272 111f6bb0   8ad0   -   1  klmmod (lock mgr common module)
273 111ff568  88d90 106   1  nfs (NFS syscall, client, and common)
273 111ff568  88d90 106   1  nfs (NFS syscall, client, and common)
273 111ff568  88d90  25   1  nfs (network filesystem)
273 111ff568  88d90   7   1  nfs (network filesystem version 2)
273 111ff568  88d90  26   1  nfs (network filesystem version 3)
273 111ff568  88d90  27   1  nfs (network filesystem version 4)
274 112859c0   4948   -   1  rpcsec (kernel RPC security module.)
275 1128a138   9830 231   1  sol_ucma (Solaris User RDMACM driver)
276 112936c8  1fc80   -   1  sol_ofs (Solaris OFS Misc module)
278 112b2d80    5a8 246   1  sy (Indirect driver for tty 'sy')
281 112b6038   75b0  23   1  uvfs (User virtual filesystem)
281 112b6038   75b0 274   1  uvfs (User virtual file system driver)
288 11bffe18    1f8   -   1  fssnap_if (File System Snapshot Interface)
289 113008f0  38e80   2   1  ufs (filesystem for ufs)
290 11337f00  36108 107   1  ipf (IP Filter: v4.1.9)
292 1136d2c8   1bf0 132   1  logindmux (logindmux driver)
296 11380d00    ee0 186   1  ptm (Master streams driver 'ptm')
297 113819a8    e20 187   1  pts (Slave Stream Pseudo Terminal dr)
298 11382598   4b78 235   1  sppp (PPP 4.0 mux)
299 11386980   37e0   -   1  sppptun (PPP 4.0 tunnel module)
299 11386980   37e0 236   1  sppptun (PPP 4.0 tunnel driver)
304 113ebe80   74b8  28   1  autofs (filesystem for autofs)
304 113ebe80   74b8 228   1  autofs (AUTOFS syscall)
304 113ebe80   74b8 228   1  autofs (AUTOFS syscall (32-bit))
305 7bc00000   fb90   -   1  c2audit (Solaris Auditing (C2))
306 113f3078   1970 207   1  pset (processor sets)
306 113f3078   1970 207   1  pset (32-bit pset(2) syscall)
307 11bfef50    e88  71   1  acctctl (acctctl system call)
307 11bfef50    e88  71   1  acctctl (32-bit acctctl system call)
308 11b3bd90   1688   -   1  ptem (pty hardware emulator)

 /etc/pam.conf is all commented out.

root@all-bmsdb-p01:/etc# cd /etc/pam.d
root@all-bmsdb-p01:/etc/pam.d# ls -ltr 
total 64
-rw-r--r--   1 root     root         258 Aug  5  2013 gdm-autologin
-rw-r--r--   1 root     root         192 Aug  5  2013 ktelnet
-rw-r--r--   1 root     root         323 Aug  5  2013 rsh
-rw-r--r--   1 root     root         189 Aug  5  2013 krsh
-rw-r--r--   1 root     root         192 Aug  5  2013 krlogin
drwxr-xr-x   3 root     root          26 Mar 10  2016 pam.d
-rw-r--r--   1 root     root         539 Jul  6 12:48 login
-rw-r--r--   1 root     root        1200 Jul  6 12:48 tpdlogin
-rw-r--r--   1 root     root         499 Jul  6 12:48 ppp
-rw-r--r--   1 root     root         535 Jul  6 12:48 pfexec
-rw-r--r--   1 root     root         545 Jul  6 12:48 rlogin
-rw-r--r--   1 root     root         318 Jul  6 12:48 cups
-rw-r--r--   1 root     root        2143 Jul  6 12:48 other
-rw-r--r--   1 root     root         318 Jul  6 12:48 cron
-rw-r--r--   1 root     root         980 Jul  6 12:48 passwd
-rw-r--r--   1 root     root         361 Jul  6 12:48 login.lwidentity.orig
-rw-r--r--   1 root     root         862 Jul  6 12:48 tpdlogin.lwidentity.orig
-rw-r--r--   1 root     root         321 Jul  6 12:48 ppp.lwidentity.orig
-rw-r--r--   1 root     root         462 Jul  6 12:48 pfexec.lwidentity.orig
-rw-r--r--   1 root     root         367 Jul  6 12:48 rlogin.lwidentity.orig
-rw-r--r--   1 root     root         245 Jul  6 12:48 cups.lwidentity.orig
-rw-r--r--   1 root     root        1827 Jul  6 12:48 other.lwidentity.orig
-rw-r--r--   1 root     root         245 Jul  6 12:48 cron.lwidentity.orig
-rw-r--r--   1 root     root         743 Jul  6 12:48 passwd.lwidentity.orig

**Comment by rbest-bt** [comment]
The error indicates that pam was not configured. This was due to an unknown pam module 'pam_tty_tickets.so.1'. On the safe side we do not configure anything. PAM needs to be configured in order for PBIS to work.

Two options:
1. issue domainjoin with --ignore PAM then manually add lsass to the pam config files.
2. Comment out the line containing pam_tty_tickets.so.1, issue the domainjoin - should be no error - then try to add it back in

NOTE: Editing your pam.conf manually is dangerous and can break the ability to login. Strong knowledge of PAM is recommended.

**Comment by AMayet12** [comment]
Good day,

I have a similar issue with my Solaris 10 installation. Install and domain join was successful. However domain users that are part of the cell cannot authenticate. getent passwd output finds the domain user in the cell and find-user-by-name finds user as well and NO restriction.

Below is the pam.conf file after joining the domain. 

[root@<<hostname>> etc]# cat pam.conf
#
#ident  "@(#)pam.conf   1.32    11/04/08 SMI"
#
# Copyright (c) 1996, 2011, Oracle and/or its affiliates. All rights reserved.
#
# PAM configuration
#
# Unless explicitly defined, all services use the modules
# defined in the "other" section.
#
# Modules are defined with relative pathnames, i.e., they are
# relative to /usr/lib/security/$ISA. Absolute path names, as
# present in this file in previous releases are still acceptable.
#
# Authentication management
#
# login service (explicit because of pam_dial_auth)
#
login   auth requisite          pam_lsass.so            set_default_repository
login   auth requisite          pam_lsass.so            smartcard_prompt                try_first_pass
login   auth requisite          pam_authtok_get.so.1            try_first_pass
login   auth sufficient         pam_lsass.so            try_first_pass
login   auth required           pam_dhkeys.so.1
login   auth required           pam_unix_cred.so.1
login   auth required           pam_unix_auth.so.1
login   auth required           pam_dial_auth.so.1
#
# rlogin service (explicit because of pam_rhost_auth)
#
rlogin  auth sufficient         pam_rhosts_auth.so.1
rlogin  auth requisite          pam_lsass.so            set_default_repository
rlogin  auth requisite          pam_lsass.so            smartcard_prompt                try_first_pass
rlogin  auth requisite          pam_authtok_get.so.1            try_first_pass
rlogin  auth sufficient         pam_lsass.so            try_first_pass
rlogin  auth required           pam_dhkeys.so.1
rlogin  auth required           pam_unix_cred.so.1
rlogin  auth required           pam_unix_auth.so.1
#
# Kerberized rlogin service
#
krlogin auth required           pam_unix_cred.so.1
krlogin auth required           pam_krb5.so.1
#
# rsh service (explicit because of pam_rhost_auth,
# and pam_unix_auth for meaningful pam_setcred)
#
rsh auth sufficient             pam_rhosts_auth.so.1
rsh auth required               pam_unix_cred.so.1
#
# Kerberized rsh service
#
krsh    auth required           pam_unix_cred.so.1
krsh    auth required           pam_krb5.so.1
#
# Kerberized telnet service
#
ktelnet auth required           pam_unix_cred.so.1
ktelnet auth required           pam_krb5.so.1
#
# PPP service (explicit because of pam_dial_auth)
#
ppp auth requisite              pam_lsass.so            set_default_repository
ppp auth requisite              pam_lsass.so            smartcard_prompt                try_first_pass
ppp auth requisite              pam_authtok_get.so.1            try_first_pass
ppp auth sufficient             pam_lsass.so            try_first_pass
ppp auth required               pam_dhkeys.so.1
ppp auth required               pam_unix_cred.so.1
ppp auth required               pam_unix_auth.so.1
ppp auth required               pam_dial_auth.so.1
#
# Default definitions for Authentication management
# Used when service name is not explicitly mentioned for authentication
#
other   auth requisite          pam_lsass.so            set_default_repository
other   auth requisite          pam_lsass.so            smartcard_prompt                try_first_pass
other   auth requisite          pam_authtok_get.so.1            try_first_pass
other   auth sufficient         pam_lsass.so            try_first_pass
other   auth required           pam_dhkeys.so.1
other   auth required           pam_unix_cred.so.1
other   auth required           pam_unix_auth.so.1
#
# passwd command (explicit because of a different authentication module)
#
passwd  auth requisite          pam_lsass.so            set_default_repository
passwd  auth sufficient         pam_passwd_auth.so.1
passwd  auth requisite          pam_lsass.so            smartcard_prompt                try_first_pass
passwd  auth sufficient         pam_lsass.so            try_first_pass
passwd  auth required           pam_deny.so
#
# cron service (explicit because of non-usage of pam_roles.so.1)
#
cron    account required        pam_lsass.so    unknown_ok
cron    account sufficient      pam_lsass.so
cron    account required        pam_unix_account.so.1
#
# Default definition for Account management
# Used when service name is not explicitly mentioned for account management
#
other   account requisite       pam_roles.so.1
other   account required        pam_lsass.so    unknown_ok
other   account sufficient      pam_lsass.so
other   account required        pam_unix_account.so.1
#
# Default definition for Session management
# Used when service name is not explicitly mentioned for session management
#
other   session sufficient      pam_lsass.so
other   session required        pam_unix_session.so.1
#
# Default definition for Password management
# Used when service name is not explicitly mentioned for password management
#
other   password required       pam_dhkeys.so.1
other   password requisite      pam_authtok_get.so.1
# Password construction requirements apply to all users.
# Remove force_check to have the traditional authorized administrator
# bypass of construction requirements.
other   password sufficient     pam_lsass.so    try_first_pass  use_authtok
other   password requisite      pam_authtok_check.so.1 force_check
other   password required       pam_authtok_store.so.1
#
# Support for Kerberos V5 authentication and example configurations can
# be found in the pam_krb5(5) man page under the "EXAMPLES" section.
#
[root@<<hostname>> etc]#

All seems to be in order. However authentication still fails. I have picked up that the entry in the host file was incorrect and required to be changed. Also scp and sftp fails which, to me, means sshd_config may be the issue.

Any assistance would be appreciated.
