### ISSUE TITLE
how to find SID from a Uid

### ISSUE THREAD

**Issue by jelayeb** [BeyondTrust/pbis-open#141]
Hi 

i have a strange request here, but is it possible to find the SID from a UID. 
the user is already removed and not exist anymore, but there are many files owned to UID 569933899 and i want to know to which user was this UID. 
i do have a backup from all SIDs on the Active Directory side, so if i could generate the SID out of the UID then it will be good. 

Thanks

**Comment by RBoulton-BT** [comment]
It's easy to find the RID  (i.e. the last part of the SID) S-1-5-21-0123456789-0123456789-0123456789-<RID> assuming you have less than approx. 500k users/groups/computers

RID = UID & 0x7FFFF

So for example using Windows calc.exe select programmer mode. Using DEC enter the UID, select HEX and click "And" then enter 7FFFF then "=", reselect DEC and that should be your RID. 

If that doesn't help because you have the same RID in multiple domains let us know and we can explain how to determine which domain the UID belongs to, that's a little more complicated but I think someone posted some example code already for calculating the UID from a SID.

**Comment by jelayeb** [comment]
thanks for your explanation, unfortunately, it didn't work with me, because as you said, it was from a different domain,  and that domain is completely removed,

**Comment by RBoulton-BT** [comment]
So if you know what domain the user was in, you probably know the first part of the SID, it's the same for all users in that domain. The RID is the unique bit on the end of the SID.

You say you have a backup of all the SIDs on the AD side, you should find all these start with the same data and it's just the final RID part that changes. You should just be able to search for the one that ends in the RID you calculated.

I may not be understanding what you are asking.

**Comment by jelayeb** [comment]
I searched and found nothing, 
correct me if I'm doing something wrong 
UID=569933899  the calculated RID is 211097

**Comment by RBoulton-BT** [comment]
I get a RID of 32843, would that work?

**Comment by jelayeb** [comment]
the problem here that i was using the calculater under Linuxmint, and it was givving me a wrong number. 
now i tried it on windows calc.exe and i got the exact number. 

strange

**Comment by jelayeb** [comment]
just short info, there was no issue with the calculator in Linux mint, the issue was that you have to hit Enter after you convert from dec to hex, otherwise it will not be converted. 

Thanks

**Comment by jelayeb** [comment]
hi
I am not opening this case again, i\m just wondering what if I have the windows RID how can I calculate the Linux ID out of it.
