### ISSUE TITLE
Upgrade to kerberos 5.17?

### ISSUE THREAD

**Issue by 29217321** [BeyondTrust/pbis-open#228]
http://web.mit.edu/kerberos/krb5-1.17/

Do we have a plan to upgrade the Kerberos foundations to krb5-1.17 version?
(The current used Kerberos was just updated in 2011 and it was krb5-1.9 only?)

**Comment by rbest-bt** [comment]
Yes, it's currently in the works and is planned for later this year. We are also changing how we compile with 3rd party libraries to prevent the issue that caused the delay with updating it.

**Comment by 29217321** [comment]
Thanks for the reply and information.

**Comment by 29217321** [comment]
Looking forward to that.

**Comment by opti545** [comment]
Any updates?

**Comment by rbest-bt** [comment]
This required a significant change to work across the platforms we support. With that, we decided to fork away from open to achieve this. As of now, there are no plans to update them in pbis-open. We are currently working on a method to test the community's Pull Request so that we can start accepting them.

**Comment by 29217321** [comment]
Do we have a news on this point? thanks

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
