### ISSUE TITLE
Instructions request: MySQL authentication via Powerbroker Open

### ISSUE THREAD

**Issue by Comnenus** [BeyondTrust/pbis-open#313]
Version: 9.1.0.551

Hello,

Is it possible to have pbis-open handle mysql authentication using domain accounts via pam or some other mechanism?  I haven't come across any documentation that answers this either way.

Thanks!

**Comment by davidmorash** [comment]
pbis does supply pam modules so this should just work if MySQL is configured to use PAM. However PAM authentication in MySQL appears to be a MySQL Enterprise feature.
 See https://dev.mysql.com/doc/refman/8.0/en/pam-pluggable-authentication.html#:~:text=PAM%20pluggable%20authentication%20is%20an%20extension%20included%20in,PAM%20(Pluggable%20Authentication%20Modules)%20to%20authenticate%20MySQL%20users.

**Comment by Comnenus** [comment]
I should have specified, I am using Percona MySQL.  They do have some documentation here for using pam: https://www.percona.com/doc/percona-server/8.0/security/pam_plugin.html#pam-plugin

I was hoping I could replace the pam_unix.so lines with pam_lsass.so but it didn't work - even root couldn't log in after that.  Do you have any suggestions of what the /etc/pam.d/mysqld file should look?

**Comment by davidmorash** [comment]
I'd check out /etc/pam.d (if it exists) and /etc/pam.conf and duplicate the entries for sshd, replacing sshd with mysqld. 

So if you pam.conf has entries for sshd, copy paste them and replace sshd with mysqld.  If /etc/pam.d/sshd exists, then copy that to /etc/pam.d/mysqld. 

n.b. the pam_lsass entries need to precede pam_unix entries so that pbis is tries to authenticate first before pam_unix is tried. The pam_lsass entries are marked as sufficient so that if authenticating succeeds, it doesn't bother trying pam_unix.  pam_unix entries are usually marked as required meaning if they fail, the authentication will fail.  PAM is considerably more complicated that that, but I wanted to give you some basic information so you have some understanding of why pbis configures the pam stack the way it does.

**Comment by rbest-bt** [comment]
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
