### ISSUE TITLE
Specifying domain controllers

### ISSUE THREAD

**Issue by maxiepax** [BeyondTrust/pbis-open#36]
As the forum has been down for quite a while im resorting to posting this as an error.

Our AD setup currently has multiple companies/forests in it, and our client machines can only reach the AD servers of the local company. It seems that open-pbis doesn't like that it can't query any DC it likes, ( we have this issue with ldap logins as well ), and thus im trying to find out if there is any way i can specify manually which AD servers to use in pbis?

this is the error i get:
sudo /opt/pbis/bin/config UserDomainPrefix MYDOMAIN
Problem executing '/opt/pbis/bin/ad-cache --delete-all >/dev/null 2>/dev/null'
Error: Error returned by external program

the error is the same for any command i run, joining the domain went fine though.

**Comment by rbest-bt** [comment]
In the next release we have a fix for setting config options before you join a domain.

I'm confused about your issue. Are you joined to a specific domain? If you are joined but there are DC in the domain that are not reachable (due to networking) you can use the config tools blacklist option if the DC are not on a separate site.

**Comment by rbest-bt** [comment]
8.5.4 was release with config tool fix when used before a domainjoin. For the ad-cache error see issue #3. Black listing was mentioned and there is a plan to add white listing in the future.

**Comment by CanadianRepublican** [comment]
Actually I got around these issues by setting the config options before joining the domain.
